### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by liutingfenga** [Micalhl/TrHologram#14]
版本：1.12.2
服务端：CatServer
问题：1.悬浮物漂浮到全息图上方空中。2.使用重载命令报错
服务端启动加载时候的报错：
[18:18:31] [Server thread/ERROR]: Error occurred while enabling TrHologram v2.4-pre19 (Is it up to date?)
java.lang.NullPointerException: null
        at me.arasple.mc.trhologram.api.Position$Companion.fromLocation(Position.kt:58) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[?:?]
        at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:36) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-4ebe242]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

[19:47:22] [Server thread/INFO]: TingFeng issued server command: /trhologram reload
[19:47:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trhologram' in plugin TrHologram v2.4-pre19
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-4ebe242]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[CraftServer.class:git-CatServer-1.12.2-4ebe242]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1600) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1443) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:833) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:770) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at me.arasple.mc.trhologram.api.Position$Companion.fromLocation(Position.kt:58) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[?:?]
        at me.arasple.mc.trhologram.module.command.impl.CommandReload.commandReload(CommandReload.kt:52) ~[?:?]
        at me.arasple.mc.trhologram.module.command.impl.CommandReload.access$commandReload(CommandReload.kt:17) ~[?:?]
        at me.arasple.mc.trhologram.module.command.impl.CommandReload$command$1$2.invoke(CommandReload.kt:30) ~[?:?]
        at me.arasple.mc.trhologram.module.command.impl.CommandReload$command$1$2.invoke(CommandReload.kt:29) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:179) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:86) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:98) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:21) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:67) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-4ebe242]
        ... 15 more

**Comment by liutingfenga** [comment]
启动后报错
最新版本：v2.4-pre20 
[14:43:09] [Server thread/ERROR]: Error occurred while enabling TrHologram v2.4-pre20 (Is it up to date?)
java.lang.NullPointerException: null
        at me.arasple.mc.trhologram.api.Position$Companion.fromLocation(Position.kt:58) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[?:?]
        at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:36) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-04a5dca]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-04a5dca]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-04a5dca]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-04a5dca]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-04a5dca]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by Micalhl** [comment]
请提供 Hologram 配置文件内容。
