### ISSUE TITLE
TrHologram不兼容多世界

### ISSUE THREAD

**Issue by luoxiawuchen** [Micalhl/TrHologram#17]
作者你好 我在使用过程中发现全息与多世界的兼容似乎存在问题。
情况复现：
将配置文件
Location: 配置项填入多世界的世界名
例如：Location: RPG~-0.63,0.5,0.51
在此之前一切都可以正常使用，/trhd reload也没有问题 全息正常显示
**但重启服务器后插件将严重报错，无法继续使用，且输入/trhd 提示为未知的命令（指令没有被成功注册）**
使用的多世界插件为：Multiverse

报错日志（里面提及到了位置相关的语句）：
[22:46:46 ERROR]: 启用 TrHologram v2.4-pre20 时发生错误 (它是最新的吗？)
 java.lang.NullPointerException: null
        at me.arasple.mc.trhologram.api.**Position**$Companion.fromLocation(Position.kt:58) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[?:?]
        at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:36) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by shuiqing2046** [comment]
在1.18.1上问题迟迟无法解决,于是重新找了个功能完全一样的插件,完美替代
https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-papi-support-no-dependencies.96927/

**Comment by ZoruaFox** [comment]
问题补充：这个问题在Loliserver呈现一模一样的错误，并且补充一个细节：用Plugman重载插件后恢复正常，但重启又会报错，且与Issues发布者呈现同样的NullPointerException空指针异常报错 @luoxiawuchen
