### ISSUE TITLE
在Airplane-1.17.1中无法启用

### ISSUE THREAD

**Issue by FrankHan052176** [Micalhl/TrHologram#18]
### **Server Version:**
Airplane version git-Airplane-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 317e61b on HEAD)
### **System:**
Windows Server 2016
### **Java Version:**
  openjdk version "16.0.2" 2021-07-20
  OpenJDK Runtime Environment Corretto-16.0.2.7.1 (build 16.0.2+7)
  OpenJDK 64-Bit Server VM Corretto-16.0.2.7.1 (build 16.0.2+7, mixed mode, sharing)
### **Plugin Version:**
2.4-pre20 (the verison of plugin.yml)
### **Log:** 
  [11:07:46 INFO]: [TrHologram] Enabling TrHologram v2.4-pre20
  [11:07:46 INFO]: [TrHologram] HOOK | 软依赖 SkinsRestorer 已兼容.
  [11:07:46 INFO]: [TrHologram] HOOK | 软依赖 TrMenu 已兼容.
  [11:07:46 INFO]: [TrHologram] FINE | 0 个全息图已加载 (6.2921 ms)
  [11:07:46 INFO]: [TrHologram] INFO | 插件启用. 当前运行版本 2.4-pre20.
  [11:07:47 ERROR]: Error occurred while enabling TrHologram v2.4-pre20 (Is it up to date?)
  java.lang.ClassCastException: Cannot cast java.lang.String to net.kyori.adventure.text.Component
          at java.lang.Class.cast(Class.java:3818) ~[?:?]
          at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
          at me.arasple.mc.trhologram.taboolib.common.reflect.Ref.put(Ref.kt:37) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.common.reflect.Reflex.set(Reflex.kt:69) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.common.reflect.Reflex.write(Reflex.kt:36) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:142) ~[TrHologram-2.4- pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:138) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:78) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:63) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[TrHologram-2.4-pre20.jar:?]
          at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:64) ~[TrHologram-2.4-pre20.jar:?]
          at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-95]
          at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-95]
          at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Airplane-95]
          at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Airplane-95]
          at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Airplane-95]
          at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Airplane-95]
          at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
          at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-95]
          at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
          at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by kikozz** [comment]
Paper 1.17.1 也会出现同样的问题
