### ISSUE TITLE
关于修复版TrHologram在1.18 Paper上的一些问题反馈

### ISSUE THREAD

**Issue by shuiqing2046** [Micalhl/TrHologram#21]
应该是没完全适配的原因,目前在1.18上总体正常,但会出现以下一些问题.
①.悬浮物品例如头颅之类的不会显示.
②.含随机性的大概率对非OP玩家,悬浮信息不可见.
③.可视距离随机性的出现问题,超出可视设置后依旧可见，同一半径内的多个悬浮信息会存在超出可视距离隐藏和超出可视距离不隐藏的怪异现象.能隐藏的悬浮信息视距较短,不能隐藏的悬浮信息大于或等于6.
④.点击悬浮信息执行命令不可以,完全没有任何反应,后台也无报错信息.

**Comment by shuiqing2046** [comment]
突然冒出这个.
`[15:39:38 INFO]: [TrHologram] Enabling TrHologram v2.4-pre23
[15:39:38 ERROR]: Error occurred while enabling TrHologram v2.4-pre23 (Is it up to date?)
java.lang.NullPointerException: null
        at me.arasple.mc.trhologram.api.Position$Companion.fromLocation(Position.kt:58) ~[TrHologram-2.4-pre23.jar:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[TrHologram-2.4-pre23.jar:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[TrHologram-2.4-pre23.jar:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[TrHologram-2.4-pre23.jar:?]
        at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:36) ~[TrHologram-2.4-pre23.jar:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[TrHologram-2.4-pre23.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-52]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-52]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-52]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:39:38 INFO]: [TrHologram] Disabling TrHologram v2.4-pre23`

**Comment by shuiqing2046** [comment]
在1.18.1上问题迟迟无法解决,理解作者的忙碌和辛苦,但是习惯了这个插件,现在功能缺失太严重,于是找了个新的替换插件:
https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-papi-support-no-dependencies.96927/

**Comment by ddos-ling** [comment]
我在 1.17.1 同样遇到全息物品无法显示问题
