### ISSUE TITLE
在1.18与Trmenu冲突!

### ISSUE THREAD

**Issue by lanzhihry** [Micalhl/TrHologram#22]
spigot最新版本,加载时错误
`[15:39:19] [Server thread/ERROR]: Could not load 'plugins\TrHologram-2.4-pre23.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.LinkageError: loader constraint violation in interface itable initialization for class me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter: when selecting method 'void com.electronwill.nightconfig.core.io.ConfigWriter.write(com.electronwill.nightconfig.core.UnmodifiableConfig, java.io.Writer)' the class loader org.bukkit.plugin.java.PluginClassLoader @4426531f for super interface com.electronwill.nightconfig.core.io.ConfigWriter, and the class loader org.bukkit.plugin.java.PluginClassLoader @6087f669 of the selected method's class, me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter have different Class objects for the type com.electronwill.nightconfig.core.UnmodifiableConfig used in the signature (com.electronwill.nightconfig.core.io.ConfigWriter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4426531f, parent loader java.net.URLClassLoader @5b80350b; me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6087f669, parent loader java.net.URLClassLoader @5b80350b)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization for class me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter: when selecting method 'void com.electronwill.nightconfig.core.io.ConfigWriter.write(com.electronwill.nightconfig.core.UnmodifiableConfig, java.io.Writer)' the class loader org.bukkit.plugin.java.PluginClassLoader @4426531f for super interface com.electronwill.nightconfig.core.io.ConfigWriter, and the class loader org.bukkit.plugin.java.PluginClassLoader @6087f669 of the selected method's class, me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter have different Class objects for the type com.electronwill.nightconfig.core.UnmodifiableConfig used in the signature (com.electronwill.nightconfig.core.io.ConfigWriter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4426531f, parent loader java.net.URLClassLoader @5b80350b; me.arasple.mc.trhologram.taboolib.module.configuration.YamlWriter is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6087f669, parent loader java.net.URLClassLoader @5b80350b)
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredField(Class.java:2608) ~[?:?]
	at me.arasple.mc.trhologram.taboolib.common.io.Project1Kt.getInstance(Project1.kt:45) ~[?:?]
	at me.arasple.mc.trhologram.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:87) ~[?:?]
	at me.arasple.mc.trhologram.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
	at me.arasple.mc.trhologram.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:123) ~[?:?]
	at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	... 7 more`

**Comment by lanzhihry** [comment]
我试了一下,如果不安装Trmenu就不会冲突,都是Tr的插件竟然会冲突,让我意想不到

**Comment by lanzhihry** [comment]
应该是软依赖trmenu的原因吧
