### ISSUE TITLE
与PlotSquared地皮插件冲突问题

### ISSUE THREAD

**Issue by luoxiawuchen** [Micalhl/TrHologram#35]
当同时安装 TrHologram 与 PlotSquared 与 worldedit（ps地皮需要创世神作为前置） 会复现之前已经关闭的mv多世界问题

服务端：spigot、paper均测试过都有这样的问题
版本：1.16~1.18均有（应该和版本无关）

bug复现步骤
1、安装相关插件
2、启动服务器，tr全息无报错，用mv创建一个世界test
3、在这个test世界创建全息图，无报错
4、重启服务器，tr全息插件无法正常被载入，并报错
5、简单来说，当非主世界有全息时，启动服务器tr插件就会无法被正常载入

错误报告：
[18:44:02] [Server thread/INFO]: [TrHologram] Enabling TrHologram v2.4-pre26
[18:44:02] [Server thread/INFO]: [TrHologram] HOOK | 软依赖 TrMenu 已兼容.
[18:44:02] [Server thread/ERROR]: Error occurred while enabling TrHologram v2.4-pre26 (Is it up to date?)
java.lang.NullPointerException: null
        at me.arasple.mc.trhologram.api.Position$Companion.fromLocation(Position.kt:58) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:112) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:78) ~[?:?]
        at me.arasple.mc.trhologram.module.conf.HologramLoader.load(HologramLoader.kt:69) ~[?:?]
        at me.arasple.mc.trhologram.TrHologram.onEnable(TrHologram.kt:36) ~[?:?]
        at me.arasple.mc.trhologram.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]

PlotSquared - 源码 
https://github.com/IntellectualSites/PlotSquared/

打包好的服务端（以便测试）
https://tmp.link/f/62c5768606e42

**Comment by Micalhl** [comment]
服务端我这里下载不下来。
我尝试将 PlotSquared 也加入软依赖，在其后加载，我也不确定，可以试一下。使用 pre28 版本。

**Comment by luoxiawuchen** [comment]
还是不行噢
我将服务端链接私发给您吧
已经配置好了环境
谢谢作者
或者说有没有可能是地皮插件那边的问题


下载链接不会限速
下载1：https://tmp.link/f/62e60c9257924
下载2：https://caiyun.139.com/m/i?015CHXzw3Dxpd&nbsp; 提取码:qc5R




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月31日(星期天) 中午12:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Micalhl/TrHologram] 与PlotSquared地皮插件冲突问题 (Issue #35)





 
服务端我这里下载不下来。
 我尝试将 PlotSquared 也加入软依赖，在其后加载，我也不确定，可以试一下。使用 pre28 版本。
